### ISSUE TITLE
Occasional wait test fail

### ISSUE THREAD

**Issue by viraptor** [carllerche/nix-rust#260] opened 2016-01-31 22:08 UTC
Very occasionally when testing, I run into this test failure. Seems timing / race related.
```
test test_unistd::test_execve ... FAILED
test test_unistd::test_wait ... FAILED

failures:

---- test_unistd::test_execve stdout ----
        thread 'test_unistd::test_execve' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(ECHILD)', ../src/libcore/result.rs:741

---- test_unistd::test_wait stdout ----
        thread 'test_unistd::test_wait' panicked at 'assertion failed: `(left == right)` (left: `Ok(Exited(2837, 0))`, right: `Ok(Exited(2843, 0))`)', test/test_unistd.rs:41


failures:
    test_unistd::test_execve
    test_unistd::test_wait
```

**Comment by kamalmarhubi** [comment] 2016-01-31 23:00
Closing this as a dupe of https://github.com/carllerche/nix-rust/issues/251

Thanks for the report though! I'm glad to know it wasn't just me...

**Closed by kamalmarhubi** 2016-01-31 23:00 UTC
